### ISSUE TITLE
Update to cortex-m 0.5.2

### ISSUE THREAD

**Issue by chrysn** [maximeborges/svd2rust_efm32gg990#1]
I just got a mix of cortex-m crates pulled into my project from this crate's reference to 0.4.3. (That caused linker errors due to multiple definitions of CORE_PERIPHERALS).

Locally updating its cortex-m dependency to 0.5.2 did no harm to the functionality I used of it, and made the linker error go away. Would you consider bumping this crate's dependency for a 0.5.2?

**Comment by maximeborges** [comment]
Sorry for not being very reactive about this package. If you do a pull request it will be accepted tomorrow morning (UTC+1), or I will update it tomorrow night.
